# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
# Modified: relative import + AsyncInferenceStub only.
"""Client class corresponding to protobuf-defined AsyncInference service."""
import grpc
import warnings

from . import services_pb2 as lerobot_dot_transport_dot_services__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in services_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AsyncInferenceStub:
    """AsyncInference: from Robot perspective
    Robot send observations to & executes action received from a remote Policy server
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendObservations = channel.stream_unary(
                '/transport.AsyncInference/SendObservations',
                request_serializer=lerobot_dot_transport_dot_services__pb2.Observation.SerializeToString,
                response_deserializer=lerobot_dot_transport_dot_services__pb2.Empty.FromString,
                _registered_method=True)
        self.GetActions = channel.unary_unary(
                '/transport.AsyncInference/GetActions',
                request_serializer=lerobot_dot_transport_dot_services__pb2.Empty.SerializeToString,
                response_deserializer=lerobot_dot_transport_dot_services__pb2.Actions.FromString,
                _registered_method=True)
        self.SendPolicyInstructions = channel.unary_unary(
                '/transport.AsyncInference/SendPolicyInstructions',
                request_serializer=lerobot_dot_transport_dot_services__pb2.PolicySetup.SerializeToString,
                response_deserializer=lerobot_dot_transport_dot_services__pb2.Empty.FromString,
                _registered_method=True)
        self.Ready = channel.unary_unary(
                '/transport.AsyncInference/Ready',
                request_serializer=lerobot_dot_transport_dot_services__pb2.Empty.SerializeToString,
                response_deserializer=lerobot_dot_transport_dot_services__pb2.Empty.FromString,
                _registered_method=True)
